In [1]:
import numpy as np

In [27]:
import numpy as np

neuron = 4

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

class NeuralNetwork:
    def __init__(self, x, y):

        # features
        self.input = x
        print('input \n', self.input)
        print()

        #first hidden layer
        self.weights1 = np.random.rand(self.input.shape[1], neuron)
        print('weights1 \n', self.weights1)
        print()

        #second hidden layer
        self.weights2 = np.random.rand(neuron, 1)
        print('weights2 \n', self.weights2)
        print()

        #actual output
        self.y = y
        print('y \n', self.y)
        print()

        #predicted output ( y hat)
        self.output = np.zeros(self.y.shape)
        print('output \n', self.output)
        print()

    #forward propagation
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        print('layer1 \n', self.layer1)
        print()

        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        print('output \n', self.layer2)
        print()
    #backward propagation
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, (2 * (self.y - self.output) * sigmoid_derivative(self.output)))
        print('d_weights2 \n', d_weights2)
        print()
        d_weights1 = np.dot(self.input.T,
                            (np.dot(2 * (self.y - self.output) * sigmoid_derivative(self.output), d_weights2.T) *
                             sigmoid_derivative(self.layer1)))

        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        print('output \n', self.layer2)
        print()

        print('d_weights1 \n', d_weights1)

        # Updates weights with derivative slope of the loss function 
        self.weights1 += d_weights1
        self.weights2 += d_weights2

# Create X and y features
X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

nn = NeuralNetwork(X, y)
for i in range(10):
    nn.feedforward()
    nn.backprop()
    print('--------------------')
print(nn.output)


input 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights1 
 [[0.45754958 0.96845212 0.6628767  0.20508834]
 [0.19218033 0.42792931 0.38020011 0.0446783 ]
 [0.18768524 0.71316115 0.30885919 0.76117151]]

weights2 
 [[0.27979852]
 [0.22075966]
 [0.89937798]
 [0.75477873]]

y 
 [[0]
 [1]
 [1]
 [0]]

output 
 [[0.]
 [0.]
 [0.]
 [0.]]

layer1 
 [[0.54678406 0.67109928 0.57660678 0.68160803]
 [0.59384068 0.75787979 0.66575763 0.69122442]
 [0.65593584 0.84311804 0.72546536 0.72437338]
 [0.69792054 0.89182721 0.79444596 0.73320371]]

output 
 [[0.79153315]
 [0.81060625]
 [0.82762182]
 [0.84024745]]

d_weights2 
 [[0.]
 [0.]
 [0.]
 [0.]]

output 
 [[0.79153315]
 [0.81060625]
 [0.82762182]
 [0.84024745]]

d_weights1 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------
layer1 
 [[0.54678406 0.67109928 0.57660678 0.68160803]
 [0.59384068 0.75787979 0.66575763 0.69122442]
 [0.65593584 0.84311804 0.72546536 0.72437338]
 [0.69792054 0.89182721 0.79444596 0.73320371]]

output 
 [[0.791533